# Generated by Django 2.2.6 on 2019-10-24 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
