# Generated by Django 2.2.6 on 2019-10-24 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_admin'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='admin',
            new_name='staff',
        ),
    ]
