# Generated by Django 2.2.7 on 2020-01-18 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20191024_1514'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='is_superadmin',
            new_name='comp',
        ),
        migrations.AddField(
            model_name='staff',
            name='entc',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='staff',
            name='it',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='staff',
            name='mech',
            field=models.BooleanField(default=False),
        ),
    ]
