# Generated by Django 2.2.7 on 2020-02-19 13:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20200219_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='reg_no',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(10000), django.core.validators.MaxValueValidator(20000)]),
        ),
    ]
