# Generated by Django 2.2.7 on 2020-02-21 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20200219_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='document10',
            field=models.FileField(default='', upload_to='documents/user_documents/10marksheets'),
        ),
        migrations.AddField(
            model_name='profile',
            name='document12',
            field=models.FileField(default='', upload_to='documents/user_documents/12marksheets'),
        ),
        migrations.AddField(
            model_name='profile',
            name='document_last_sem',
            field=models.FileField(default='', upload_to='documents/user_documents/last_marksheets'),
        ),
    ]
