# Generated by Django 2.2.7 on 2020-01-19 03:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20200119_0554'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='comp',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='entc',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='it',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='mech',
        ),
        migrations.AddField(
            model_name='staff',
            name='branch',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='staff',
            name='emp_no',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(10000), django.core.validators.MaxValueValidator(20000)]),
        ),
        migrations.AlterField(
            model_name='student',
            name='reg_no',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(10000), django.core.validators.MaxValueValidator(20000)]),
        ),
    ]
