# Generated by Django 2.2.7 on 2020-02-27 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20200227_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='document10',
            field=models.FileField(default='documents/user_documents/default.jpg', upload_to='documents/user_documents/10marksheets'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='document12',
            field=models.FileField(default='documents/user_documents/default.jpg', upload_to='documents/user_documents/12marksheets'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='document_last_sem',
            field=models.FileField(default='documents/user_documents/default.jpg', upload_to='documents/user_documents/last_marksheets'),
        ),
    ]
