# Generated by Django 2.2.7 on 2020-05-18 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_auto_20200227_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='father_id',
            field=models.FileField(blank=True, null=True, upload_to='documents/user_documents/father_id'),
        ),
        migrations.AddField(
            model_name='profile',
            name='student_id',
            field=models.FileField(blank=True, null=True, upload_to='documents/user_documents/student_id'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='document10',
            field=models.FileField(blank=True, null=True, upload_to='documents/user_documents/10marksheets'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='document12',
            field=models.FileField(blank=True, null=True, upload_to='documents/user_documents/12marksheets'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='document_last_sem',
            field=models.FileField(blank=True, null=True, upload_to='documents/user_documents/last_marksheets'),
        ),
    ]
