# Generated by Django 2.2.7 on 2020-05-19 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_auto_20200518_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='father_rank',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='marks',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
