# Generated by Django 2.2.7 on 2020-05-20 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_auto_20200519_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='father_name',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
    ]
