# Generated by Django 2.2.7 on 2020-06-01 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_profile_father_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='attendence',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
