# Generated by Django 2.2.7 on 2020-07-31 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_profile_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='present_year',
            field=models.CharField(blank=True, default='FE', max_length=30, null=True),
        ),
    ]
