# Generated by Django 2.2.7 on 2020-07-31 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_profile_present_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='present_year',
            field=models.CharField(choices=[('FE', 'FE'), ('SE', 'SE'), ('TE', 'TE'), ('BE', 'BE')], default='FE', max_length=30),
        ),
    ]
