# Generated by Django 2.2.7 on 2020-01-13 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_auto_20200113_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholarship',
            name='img',
            field=models.ImageField(default='pics/default.png', upload_to='pics'),
        ),
    ]
