# Generated by Django 2.2.7 on 2020-02-28 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_auto_20200227_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholarship',
            name='img',
            field=models.ImageField(default='pics/scholarship_pics/default.png', upload_to='pics/scholarship_pics'),
        ),
    ]
