# Generated by Django 2.2.7 on 2020-05-18 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_application_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='application_table',
            name='applied_document10',
            field=models.FileField(blank=True, null=True, upload_to='applications/document10'),
        ),
        migrations.AddField(
            model_name='application_table',
            name='applied_document12',
            field=models.FileField(blank=True, null=True, upload_to='applications/document12'),
        ),
        migrations.AddField(
            model_name='application_table',
            name='applied_document_last_sem',
            field=models.FileField(blank=True, null=True, upload_to='applications/document_last_sem'),
        ),
        migrations.AddField(
            model_name='application_table',
            name='applied_extra1',
            field=models.FileField(blank=True, null=True, upload_to='applications/extra1'),
        ),
        migrations.AddField(
            model_name='application_table',
            name='applied_extra2',
            field=models.FileField(blank=True, null=True, upload_to='applications/extra2'),
        ),
        migrations.AddField(
            model_name='application_table',
            name='applied_father_id',
            field=models.FileField(blank=True, null=True, upload_to='applications/father_id'),
        ),
        migrations.AddField(
            model_name='application_table',
            name='applied_student_id',
            field=models.FileField(blank=True, null=True, upload_to='applications/student_id'),
        ),
    ]
