# Generated by Django 2.2.7 on 2020-06-17 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0008_scholarship_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scholarship',
            name='status',
        ),
        migrations.AddField(
            model_name='application_table',
            name='status',
            field=models.IntegerField(blank=True, default=2, null=True),
        ),
    ]
