# Generated by Django 2.2.7 on 2020-07-13 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0009_auto_20200617_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholarship',
            name='boy',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='girl',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
