# Generated by Django 2.2.7 on 2020-07-28 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0011_auto_20200726_1135'),
    ]

    operations = [
        migrations.CreateModel(
            name='session_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=0)),
                ('scholarship_id', models.IntegerField(default=0)),
                ('session', models.IntegerField(default=0)),
            ],
        ),
    ]
