# Generated by Django 2.2.7 on 2020-08-26 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0014_remove_scholarship_present_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='current_session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.IntegerField(default=0)),
            ],
        ),
    ]
