# Generated by Django 2.2.7 on 2020-09-05 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0015_current_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application_table',
            name='applied_extra1',
            field=models.FileField(blank=True, null=True, upload_to='documents/extra1'),
        ),
        migrations.AlterField(
            model_name='application_table',
            name='applied_extra2',
            field=models.FileField(blank=True, null=True, upload_to='documents/extra2'),
        ),
    ]
