# Generated by Django 2.2.7 on 2020-09-06 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0016_auto_20200905_1619'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scholarship',
            name='applicants',
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='short_description',
            field=models.CharField(max_length=40),
        ),
    ]
