# Generated by Django 2.2.7 on 2020-09-07 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0017_auto_20200906_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarship',
            name='scholarship_form',
            field=models.FileField(default='documents/scholarship_form/default_scholarship_form', upload_to='documents/scholarship_form/'),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='short_description',
            field=models.CharField(max_length=100),
        ),
    ]
