# Generated by Django 2.2.7 on 2020-09-07 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0019_auto_20200907_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholarship',
            name='scholarship_form',
            field=models.FileField(default='documents/scholarship_form/default_scholarship_form.pdf', upload_to='documents/scholarship_form/'),
        ),
    ]
