# Generated by Django 2.2.7 on 2020-09-08 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0020_auto_20200908_0515'),
    ]

    operations = [
        migrations.AddField(
            model_name='application_table',
            name='applied_scholarship_form',
            field=models.FileField(blank=True, null=True, upload_to='applications/applied_scholarship_form'),
        ),
        migrations.AlterField(
            model_name='application_table',
            name='applied_extra1',
            field=models.FileField(blank=True, null=True, upload_to='applications/extra1'),
        ),
        migrations.AlterField(
            model_name='application_table',
            name='applied_extra2',
            field=models.FileField(blank=True, null=True, upload_to='applications/extra2'),
        ),
    ]
