# Generated by Django 2.2.7 on 2020-09-10 14:41

from django.db import migrations, models
import homepage.models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0022_auto_20200910_0649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application_table',
            name='applied_extra1',
            field=models.FileField(blank=True, null=True, upload_to='applications/extra1', validators=[homepage.models.file_size]),
        ),
        migrations.AlterField(
            model_name='application_table',
            name='applied_extra2',
            field=models.FileField(blank=True, null=True, upload_to='applications/extra2', validators=[homepage.models.file_size]),
        ),
        migrations.AlterField(
            model_name='application_table',
            name='applied_scholarship_form',
            field=models.FileField(blank=True, null=True, upload_to='applications/applied_scholarship_form', validators=[homepage.models.file_size2]),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='document',
            field=models.FileField(upload_to='documents/scholarship_broucher/', validators=[homepage.models.file_size2]),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='img',
            field=models.ImageField(default='pics/scholarship_pics/default.png', upload_to='pics/scholarship_pics', validators=[homepage.models.file_size]),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='scholarship_form',
            field=models.FileField(default='documents/scholarship_form/default_scholarship_form.pdf', upload_to='documents/scholarship_form/', validators=[homepage.models.file_size2]),
        ),
    ]
